default:
  solr_core: api_lc
  es_type: lewisandclark

  # all media comes from production server
  media_base: https://cdrhmedia.unl.edu

  tei_solr_xsl: collections/lewisandclark/scripts/solr_transform_tei.xsl
  tei_html_xsl: collections/lewisandclark/scripts/tei.p5.xsl

  variables_solr:
    slug: lewisandclark
    site_url: https://lewisandclarkjournals.unl.edu
    # not specifying image size for lewis and clark
    # since there are four sizes across multiple types

