default:
  solr_core: api_lc
  collection: lewisandclark
  media_base: https://cdrhmedia.unl.edu

  tei_solr_xsl: scripts/overrides/tei_to_solr.xsl
  tei_html_xsl: scripts/overrides/tei_to_html.xsl

  variables_solr:
    slug: lewisandclark
    site_url: https://lewisandclarkjournals.unl.edu
